apiVersion: v2
name: pgwd
description: Postgres Watch Dog - monitor PostgreSQL connection counts and notify via Slack/Loki
type: application
version: 0.1.5
appVersion: "v0.5.10"
keywords:
  - postgres
  - monitoring
  - slack
  - loki
home: https://github.com/hrodrig/pgwd
sources:
  - https://github.com/hrodrig/pgwd
maintainers:
  - name: Hermes Rodriguez
    url: https://github.com/hrodrig/pgwd
kubeVersion: ">=1.28.0"
