apiVersion: v2
name: pgwd
description: Postgres Watch Dog - monitor PostgreSQL connections; Slack/Loki; optional SQLite history, HTTP /healthz and Prometheus /metrics
type: application
version: 0.1.8
appVersion: "v0.6.4"
keywords:
  - postgres
  - monitoring
  - slack
  - loki
home: https://github.com/hrodrig/pgwd
sources:
  - https://github.com/hrodrig/pgwd
maintainers:
  - name: Hermes Rodriguez
    url: https://github.com/hrodrig/pgwd
kubeVersion: ">=1.28.0"
