{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) (or .Values.secrets.dbUrl .Values.secrets.slackWebhook .Values.secrets.lokiUrl) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgwd.fullname" . }}-secrets
  labels:
    {{- include "pgwd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.dbUrl }}
  url: {{ .Values.secrets.dbUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.slackWebhook }}
  slack-webhook: {{ .Values.secrets.slackWebhook | quote }}
  {{- end }}
  {{- if .Values.secrets.lokiUrl }}
  loki-url: {{ .Values.secrets.lokiUrl | quote }}
  {{- end }}
{{- end }}
